/// Generated by tool/richtext_runtime_prepare.dart — do not hand-edit.
library;

const int kRichTextRuntimeProtocolVersion = 2;
const int kRichTextHostEnvelopeVersion = 1;

class RichTextRuntimeManifest {
  const RichTextRuntimeManifest({
    required this.protocolVersion,
    required this.hostEnvelopeVersion,
    required this.buildId,
    required this.webEntry,
    required this.webEntrySha256,
    this.sourceCommit,
    this.branch,
    this.branchIdentity,
    this.releaseTag,
    this.pipelineId,
    this.pipelineIid,
    this.archiveSha256,
    this.contentSha256,
  });

  final int protocolVersion;
  final int hostEnvelopeVersion;
  final String buildId;
  final String webEntry;
  final String webEntrySha256;
  final String? sourceCommit;
  final String? branch;
  final String? branchIdentity;
  final String? releaseTag;
  final int? pipelineId;
  final int? pipelineIid;
  final String? archiveSha256;
  final String? contentSha256;

  String get webEntryAssetPath => 'assets/packages/flutter_quill_editor/assets/richtext_webview_runtime/$webEntry';
}

const RichTextRuntimeManifest kRichTextRuntimeManifest = RichTextRuntimeManifest(
  protocolVersion: 2,
  hostEnvelopeVersion: 1,
  buildId: "029749e5fd1135405915b358d64cf4e1aae2f55f",
  webEntry: "iframe.c2f3b2e32dca84ac.html",
  webEntrySha256: "c2f3b2e32dca84ac4c05626acd8bb02f19769eaa102635ac39ae4d2693a70767",
  sourceCommit: "029749e5fd1135405915b358d64cf4e1aae2f55f",
  branch: null,
  branchIdentity: null,
  releaseTag: "webview-runtime-artifact-029749e5fd1135405915b358d64cf4e1aae2f55f",
  pipelineId: null,
  pipelineIid: null,
  archiveSha256: "0e30b5b4ddf3147f8f08d21a2cf3baaf11675bbb712f4c621be39d4bab6c7322",
  contentSha256: "b96b6dd7ca3f24ac5f97e461863d2f8c2c5e0e23788e7c31e55dc1dc9c573d90",
);
