/// Generated by tool/richtext_runtime_prepare.dart — do not hand-edit.
library;

const int kRichTextRuntimeProtocolVersion = 1;
const int kRichTextHostEnvelopeVersion = 1;

class RichTextRuntimeManifest {
  const RichTextRuntimeManifest({
    required this.protocolVersion,
    required this.hostEnvelopeVersion,
    required this.buildId,
    required this.webEntry,
    required this.webEntrySha256,
    this.sourceCommit,
    this.branch,
    this.branchIdentity,
    this.releaseTag,
    this.pipelineId,
    this.pipelineIid,
    this.archiveSha256,
  });

  final int protocolVersion;
  final int hostEnvelopeVersion;
  final String buildId;
  final String webEntry;
  final String webEntrySha256;
  final String? sourceCommit;
  final String? branch;
  final String? branchIdentity;
  final String? releaseTag;
  final int? pipelineId;
  final int? pipelineIid;
  final String? archiveSha256;

  String get webEntryAssetPath => 'assets/packages/flutter_quill_editor/assets/richtext_webview_runtime/$webEntry';
}

const RichTextRuntimeManifest kRichTextRuntimeManifest = RichTextRuntimeManifest(
  protocolVersion: 1,
  hostEnvelopeVersion: 1,
  buildId: "2026-08-19T03:28:26.183Z",
  webEntry: "iframe.91ab26f1113b9772.html",
  webEntrySha256: "91ab26f1113b9772ac84d0c57b58321338c221aa71a290d4ec99fec77c27bb41",
  sourceCommit: "619fdc80f4db602ae2412f8606c362a18d7f8539",
  branch: "dev",
  branchIdentity: "ef260e9aa3c673af240d17a2660480361a8e081d1ffeca2a5ed0e3219fc18567",
  releaseTag: "webview-runtime-channel-dev-ef260e9aa3c673af-9",
  pipelineId: 32212239365,
  pipelineIid: 9,
  archiveSha256: "762fb8a4042073d9f381701e2d1b0b5460a165914d72e48f0dfefac910794006",
);
