/// Generated by tool/richtext_runtime_prepare.dart — do not hand-edit.
library;

const int kRichTextRuntimeProtocolVersion = 2;
const int kRichTextHostEnvelopeVersion = 1;

class RichTextRuntimeManifest {
  const RichTextRuntimeManifest({
    required this.protocolVersion,
    required this.hostEnvelopeVersion,
    required this.buildId,
    required this.webEntry,
    required this.webEntrySha256,
    this.sourceCommit,
    this.branch,
    this.branchIdentity,
    this.releaseTag,
    this.pipelineId,
    this.pipelineIid,
    this.archiveSha256,
  });

  final int protocolVersion;
  final int hostEnvelopeVersion;
  final String buildId;
  final String webEntry;
  final String webEntrySha256;
  final String? sourceCommit;
  final String? branch;
  final String? branchIdentity;
  final String? releaseTag;
  final int? pipelineId;
  final int? pipelineIid;
  final String? archiveSha256;

  String get webEntryAssetPath => 'assets/packages/flutter_quill_editor/assets/richtext_webview_runtime/$webEntry';
}

const RichTextRuntimeManifest kRichTextRuntimeManifest = RichTextRuntimeManifest(
  protocolVersion: 2,
  hostEnvelopeVersion: 1,
  buildId: "2026-08-20T07:09:21.729Z",
  webEntry: "iframe.49de9a85ecb5a005.html",
  webEntrySha256: "49de9a85ecb5a0056b03f40c0e56acb35d0084bdbcb374d8e0860fae19a1a074",
  sourceCommit: "5aaae6a0c9c98533aa9c23f770075aba8d4fb30e",
  branch: "dev",
  branchIdentity: "ef260e9aa3c673af240d17a2660480361a8e081d1ffeca2a5ed0e3219fc18567",
  releaseTag: "webview-runtime-channel-dev-ef260e9aa3c673af-9",
  pipelineId: 32212239365,
  pipelineIid: 9,
  archiveSha256: "762fb8a4042073d9f381701e2d1b0b5460a165914d72e48f0dfefac910794006",
);
